Fix bug when flaw_bug_tracker is None (on attach_cve_flaws)
```
Python 3.6.15

>>> flaw_bug_tracker = None

>>> flaw_bug_tracker.type
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'type'

>>> flaw_bug_tracker.type if hasattr(flaw_bug_tracker, 'type') else ''
''

```