ART-1466: Fix Elliott fails to attach RPMs are tagged to released tag out of order
Currently Elliott find unshipped RPMs using the following approach:
1. Get a list A of latest RPMs with candidate tag from Brew.
2. Get a list B of latest RPMs with base tag from Brew.
3. Subtract B from A.

The problem is some RPMs that are latest with the candidate tag are not considered latest with the base tag.
In such case, Elliott attempts to attach shipped RPMs but fails with the following exception:

```
$ elliott --group openshift-3.11 find-builds -k rpm  --use-default-advisory rpm
2020-01-17 06:35:26,363 INFO Data clone directory already exists, checking commit sha
2020-01-17 06:35:26,843 INFO https://github.com/openshift/ocp-build-data.git is already cloned and latest
2020-01-17 06:35:26,906 INFO Using branch from group.yml: rhaos-3.11-rhel-7
Default advisory detected: 50532
Generating list of rpms: Hold on a moment, fetching Brew builds
Refreshing for tag: rhaos-3.11-rhel-7
Refreshing for tag: rhaos-3.11-rhel-7-candidate
Gathering additional information: Brew buildinfo is required to continue
[**********************]
Refreshing for tag: rhaos-3.11-rhel-8-candidate
Refreshing for tag: rhaos-3.11-rhel-8
Gathering additional information: Brew buildinfo is required to continue
[]
[**********************]

Traceback (most recent call last):
  File "/home/nay/yuxzhu/.local/bin/elliott", line 11, in <module>
    sys.exit(main())
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/elliottlib/cli/__main__.py", line 902, in main
    cli(obj={})
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/elliottlib/cli/find_builds_cli.py", line 127, in find_builds_cli
    _attach_to_advisory(unshipped_builds, kind, advisory)
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/elliottlib/cli/find_builds_cli.py", line 249, in _attach_to_advisory
    file_types={build.nvr: [file_type] for build in builds}
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/errata_tool/erratum.py", line 695, in addBuilds
    return self.addBuildsDirect(buildlist, release, **kwargs)
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/errata_tool/erratum.py", line 674, in addBuildsDirect
    self._processResponse(r)
  File "/home/nay/yuxzhu/.local/lib/python3.6/site-packages/errata_tool/connector.py", line 256, in _processResponse
    raise ErrataException(err_msg)
errata_tool.exception.ErrataException: Erratum 50532: Unable to add build 'openshift-monitor-project-lifecycle-3.11.51-2.git.59.7b59e29.el7' which has already been released.
```

This PR filters shipped builds out of the to-be-attached list.