verify-cvp: Fix missing variable failed_optional
Fix the following error:

```
$ elliott -g openshift-4.13 --assembly rc.3 verify-cvp --all

  File "/mnt/workspace/users/yuxzhu/elliott/elliottlib/cli/verify_cvp_cli.py", line 162, in verify_cvp_cli
    if failed or failed_optional:
UnboundLocalError: local variable 'failed_optional' referenced before assignment
```