verify-attached-operators: Fix `no such tagInfo` error
We got the following error when running this command against 4.10:

```
  File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/cli/verify_attached_operators_cli.py", line 69, in verify_attached_operators_cli
    image_builds.extend(_get_shipped_images(runtime, brew_session))
  File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/cli/verify_attached_operators_cli.py", line 179, in _get_shipped_images
    released = brew.get_tagged_builds([(tag, None) for tag in tags], build_type='image', event=None, session=brew_session)
  File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/brew.py", line 46, in get_tagged_builds
    tasks.append(m.listTagged(tag, event=event, package=component_name, type=build_type))
  File "/home/jenkins/.local/lib/python3.8/site-packages/koji/__init__.py", line 3300, in __exit__
    self.call_all()
  File "/home/jenkins/.local/lib/python3.8/site-packages/koji/__init__.py", line 3282, in call_all
    raise err
koji.GenericError: No such tagInfo: 'rhaos-4.10-rhel-9-container-released'
```

(from https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fprepare-release/721/console)

This is because we don't have rhel 9 tags in 4.10.

This PR removes the hardcoded rhel versions and determines rhel versions
from branch names of image meta configs.